<?php


define( 'ROCKETLAYERSLIDER_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );

define( 'ROCKETLAYERSLIDER_PLUGIN_DIR_NAME', dirname( plugin_basename( __FILE__ ) ) );

define( 'ROCKETLAYERSLIDER_PLUGIN_INCLUDE_ADMIN_DIRECTORY_NAME', 'admin/includes' );

define( 'ROCKETLAYERSLIDER_PLUGIN_INCLUDE_PUBLIC_DIRECTORY_NAME', 'public/includes' );

define( 'ROCKETLAYERSLIDER_PLUGIN_VIEW_DIRECTORY_NAME', 'views' );

define( 'ROCKETLAYERSLIDER_PLUGIN_CSS_DIRECTORY_NAME', 'css' );

define( 'ROCKETLAYERSLIDER_PLUGIN_JS_DIRECTORY_NAME', 'js' );

define( 'ROCKETLAYERSLIDER_PLUGIN_ADMIN_DIRECTORY', ROCKETLAYERSLIDER_PLUGIN_PATH . 'admin' . DIRECTORY_SEPARATOR );

define( 'ROCKETLAYERSLIDER_PLUGIN_INCLUDE_ADMIN_DIRECTORY', ROCKETLAYERSLIDER_PLUGIN_PATH .
									  	ROCKETLAYERSLIDER_PLUGIN_INCLUDE_ADMIN_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'ROCKETLAYERSLIDER_PLUGIN_VIEW_DIRECTORY', ROCKETLAYERSLIDER_PLUGIN_PATH .
									  	ROCKETLAYERSLIDER_PLUGIN_VIEW_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'ROCKETLAYERSLIDER_PLUGIN_CSS_DIRECTORY', ROCKETLAYERSLIDER_PLUGIN_PATH .
									  	ROCKETLAYERSLIDER_PLUGIN_CSS_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'ROCKETLAYERSLIDER_PLUGIN_JS_DIRECTORY', ROCKETLAYERSLIDER_PLUGIN_PATH .
									  	ROCKETLAYERSLIDER_PLUGIN_JS_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'ROCKETLAYERSLIDER_PLUGIN_MAIN_FILE', ROCKETLAYERSLIDER_PLUGIN_PATH . 'rocketlayerslider.php' );


define( 'ROCKETLAYERSLIDER_PLUGIN_VERSION', '1.1' );

define('WPRLS_PREMIUM_ENABLED', false);